### ISSUE TITLE
Bug with nested template tags related to surrogate elements

### ISSUE THREAD

**Issue by jbgarr** [aurelia/templating#133]
It seems that with the latest version of Aurelia templating (v 0.13.5) a new bug has been introduced with nested template tags. It looks like any time a nested template tag has any sort of template controller, the error included at the bottom of this issue is thrown.

A simple way to reproduce this issue is to create something like the following:
```
<template>
  <template if.bind="true">
    Hi!
  </template>
</template>
```

I personally ran into the issue by using a template part in my nested template. It seems like any sort of template controller will cause the error (if, repeat, and replaceable).

The fix that I've used is to replace the inner `<template></template>` tag with a `<div></div>`

Unhandled promise rejection Error: You cannot place a template controller on a surrogate element.
    at ViewCompiler.compileSurrogate (http://localhost:9000/jspm_packages/github/aurelia/templating@0.13.5/index.js:1510:23)
    at ViewCompiler.compile (http://localhost:9000/jspm_packages/github/aurelia/templating@0.13.5/index.js:1410:72)
    at ViewCompiler.compileElement (http://localhost:9000/jspm_packages/github/aurelia/templating@0.13.5/index.js:1599:28)
    at ViewCompiler.compileNode (http://localhost:9000/jspm_packages/github/aurelia/templating@0.13.5/index.js:1422:23)
    at ViewCompiler.compileElement (http://localhost:9000/jspm_packages/github/aurelia/templating@0.13.5/index.js:1739:31)
    at ViewCompiler.compileNode (http://localhost:9000/jspm_packages/github/aurelia/templating@0.13.5/index.js:1422:23)
    at ViewCompiler.compileElement (http://localhost:9000/jspm_packages/github/aurelia/templating@0.13.5/index.js:1739:31)
    at ViewCompiler.compileNode (http://localhost:9000/jspm_packages/github/aurelia/templating@0.13.5/index.js:1422:23)
    at ViewCompiler.compileElement (http://localhost:9000/jspm_packages/github/aurelia/templating@0.13.5/index.js:1739:31)
    at ViewCompiler.compileNode (http://localhost:9000/jspm_packages/github/aurelia/templating@0.13.5/index.js:1422:23)(anonymous function) @ es6.promise.js:139module.exports @ $.invoke.js:6queue.(anonymous function) @ $.task.js:40run @ $.task.js:27listner @ $.task.js:31

**Comment by EisenbergEffect** [comment]
Apologies. This will get fixed top priority.

**Comment by rquast** [comment]
Hah.. just found out about this one when I tried to get ui-virtualization to work. Thanks for the quick fixes. :)

**Comment by EisenbergEffect** [comment]
Stand by. It will get fixed by tomorrow. I apologize.

**Comment by jbgarr** [comment]
Nice, the fix looks good! Thanks Rob. You guys rock!
