### ISSUE TITLE
<compose view="example.html"> throws error from UseViewStrategy

### ISSUE THREAD

**Issue by shanonvl** [aurelia/templating#146]
With templating@0.14.2, using `<compose>` with only a `view` specified:
```html
<compose view="example.html"></compose> 
```
causes the following error:
```javascript
Unhandled promise rejection TypeError: Cannot set property 'associatedModuleId' of undefined
    at t.loadViewFactory (https://github.jspm.io/aurelia/templating@0.14.2/aurelia-templating.js:2:13341)
    at e.compose (https://github.jspm.io/aurelia/templating@0.14.2/aurelia-templating.js:3:16275)
    at s (https://github.jspm.io/aurelia/templating-resources@0.14.0/compose.js:2:633)
    at e.bind (https://github.jspm.io/aurelia/templating-resources@0.14.0/compose.js:2:1782)
    at e.bind (https://github.jspm.io/aurelia/templating@0.14.2/aurelia-templating.js:3:835)
    at e.bind (https://github.jspm.io/aurelia/templating@0.14.2/aurelia-templating.js:2:17673)
    at https://github.jspm.io/aurelia/templating@0.14.2/aurelia-templating.js:3:14777
    at r (https://npm.jspm.io/core-js@0.9.18/modules/es6.promise.js:2:469)
    at https://npm.jspm.io/core-js@0.9.18/modules/es6.promise.js:2:630
    at module.exports (https://npm.jspm.io/core-js@0.9.18/modules/$.invoke.js:2:95)
```
[Here's a simple plunker](http://embed.plnkr.co/mRXx6k/preview) which illustrates the issue.

Looking in the source, it appears that the UseViewStrategy.loadViewFactory expects two arguments, the [second of which is the `compileInstruction`](https://github.com/aurelia/templating/blob/9cb96ff825519f38b9998d5936431c2b61038856/src/view-strategy.js#L55).

In this case, when called by the Composition Engine there's [only a single argument passed](https://github.com/aurelia/templating/blob/master/src/composition-engine.js#L114), which causes [compileInstruction to be null and the resulting error](https://github.com/aurelia/templating/blob/9cb96ff825519f38b9998d5936431c2b61038856/src/view-strategy.js#L60).

When I update the code in CompositionEngine to pass `instruction`, the error no longer appears:
```javascript
return instruction.view.loadViewFactory(this.viewEngine, instruction).then(viewFactory => (
```

I'm not sure if this is the correct way to resolve the problem but if so, I'm happy to send a pull request with this update.

Note, I also tried prefixing the html with `./` and received the same result:
```
<compose view="./example.html"></compose>
```

**Comment by EisenbergEffect** [comment]
Ok, I pushed a fix. Sorry, in my haste I forgot to tag this issue. You can look at the recent commits to see what I did if you are interested. I have also pushed out a new release with the fix so you should be able to jspm update and move forward. Apologies for that inconvenience.

**Comment by shanonvl** [comment]
Thank you!  Verified fixed via jspm update.
