### ISSUE TITLE
Possible breaking change with @bindable properties

### ISSUE THREAD

**Issue by RobertTheGrey** [aurelia/templating#152]
I've recently upgraded Aurelia in a project and as a result the aurelia-templating went from version 0.8.2 to 0.8.6. Previously, the code was working just fine. Now I get exceptions thrown when using @bindable on properties when the view loads like so:

```
Unhandled promise rejection TypeError: Cannot read property 'hide-completed-actions' of null
    at BindableProperty.initialize (http://localhost:42852/jspm_packages/github/aurelia/templating@0.14.4/aurelia-templating.js:2448:33)
    at new BehaviorInstance (http://localhost:42852/jspm_packages/github/aurelia/templating@0.14.4/aurelia-templating.js:2199:23)
    at HtmlBehaviorResource.create (http://localhost:42852/jspm_packages/github/aurelia/templating@0.14.4/aurelia-templating.js:2821:30)
    at http://localhost:42852/jspm_packages/github/aurelia/templating@0.14.4/aurelia-templating.js:3385:27
    at run (http://localhost:42852/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:91:43)
    at http://localhost:42852/jspm_packages/npm/core-js@0.9.18/modules/es6.promise.js:105:11
    at module.exports (http://localhost:42852/jspm_packages/npm/core-js@0.9.18/modules/$.invoke.js:6:25)
    at queue.(anonymous function) (http://localhost:42852/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:40:9)
    at Number.run (http://localhost:42852/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:27:7)
    at listner (http://localhost:42852/jspm_packages/npm/core-js@0.9.18/modules/$.task.js:31:9)
```

I have a `@bindable hideCompletedActions = true;` defined on the class and when debugging, I found the if statement on the following line:

https://github.com/aurelia/templating/blob/master/src/bindable-property.js#L133

It checks for `undefined`, but in this case the attributes array is `null` and as a result goes into the if block resulting in a null coming out of the array causing the error. I'm not sure what the attributes collection used to be equal to in previous versions, but it must not have been null and was perhaps undefined because this error was not throwing in the previous version.

**Comment by RobertTheGrey** [comment]
Reproduction is [here](https://gitter.im/Aurelia/Discuss?at=55d2000b9b45e15c42649211) and some conversation on the gitter channel  [August 18, 2015 8:52 AM](https://gitter.im/Aurelia/Discuss?at=55d2e4369b45e15c4264b0ce) and [August 18, 2015 9:02 AM](https://gitter.im/Aurelia/Discuss?at=55d2e6859b45e15c4264b11c)

**Comment by RobertTheGrey** [comment]
My temporary fix is to change this line here: https://github.com/aurelia/templating/blob/master/src/behavior-instance.js#L12 to this

`attributes = instruction.attributes ? instruction.attributes : undefined,`

but I'm not sure @EisenbergEffect would want it fixed in that way as a PR?

Or would you prefer just checking for `null` as @JeroenVinke suggests: [August 18, 2015 9:25 AM](https://gitter.im/Aurelia/Discuss?at=55d2ec11204de35b423092d5)

**Comment by JeroenVinke** [comment]
I tried checking `attributes` for `null` but then noticed that it could also be `undefined`. If I check `attributes` for a truthy value, the problem is fixed
