### ISSUE TITLE
TypeError: Cannot read property 'x' of undefined at BindableProperty.initialize

### ISSUE THREAD

**Issue by stevies** [aurelia/templating#167]
Problem since latest version. Steps to reproduce: 
```
//page1.html
<template>
      ${msg}
</template>

//page1.js
import {bindable} from 'aurelia-framework';
export class Page1 {
  @bindable msg = 'Bindable message';
}
```
Gets error: 
```
ERROR [app-router] TypeError: Cannot read property 'msg' of undefined
    at BindableProperty.initialize (http://localhost:9000/jspm_packages/github/aurelia/templating@0.15.0/aurelia-templating.js:2706:33)
    at new BehaviorInstance (http://localhost:9000/jspm_packages/github/aurelia/templating@0.15.0/aurelia-templating.js:2457:23)
    at HtmlBehaviorResource.create (http://localhost:9000/jspm_packages/github/aurelia/templating@0.15.0/aurelia-templating.js:3085:30)
    at http://localhost:9000/jspm_packages/github/aurelia/templating-router@0.16.0/router-view.js:44:49
    at f (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1415:56)
    at http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1423:13
    at b.exports (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:453:24)
    at b.(anonymous function) (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1625:11)
    at Number.f (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1596:24)
    at q (http://localhost:9000/jspm_packages/npm/core-js@0.9.18/client/shim.min.js:1600:11)
```

Appears to be caused by:  https://github.com/aurelia/templating/blob/master/src/bindable-property.js#l133
Changing to: 
```
  if (!!attributes) {
```
seems to fix things.

**Comment by EisenbergEffect** [comment]
I have copied your code exactly into the navigation skeleton project. Then, in the welcome.html file Ihave used it like this:

```
<template>
  <require from ="page1"></require>

  <page1></page1>

</template>
```

Everything works perfectly. There are no errors. Is there some other piece of information you have neglected to provide about this? Is this the way you are using it?

**Comment by stevies** [comment]
```
<template>
      ${msg}
</template>
```
That is the full contents of my page1.html.  A single binding to the @bindable msg property in the page1.js file. This is a contrived example to show the bug.

**Comment by JeroenVinke** [comment]
possibly related to https://github.com/aurelia/templating/issues/152

**Comment by stevies** [comment]
In the latest skeleton nav - if you change welcome.html to make '@bindable heading' -  
```
import {computedFrom, bindable} from 'aurelia-framework';

export class Welcome{
  @bindable heading = 'Welcome to the Aurelia Navigation App!';
  ... 
```
Then it will break in the way I describe.

**Comment by EisenbergEffect** [comment]
Ok, I can reproduce it with that. I'll investigate. Thanks!

**Comment by EisenbergEffect** [comment]
Ok, it was a bug in templating-router. It's all fixed now. If you run `jspm update` you should get the latest patch. Version for templating-router would be 0.16.1 with the fix. Sorry about the regression.
