### ISSUE TITLE
Cannot assign to bindable properties in unit tests.

### ISSUE THREAD

**Issue by txels** [aurelia/templating#204]
I have a custom element declared like this, with some bindable property:

```js
import {bindable, containerless} from 'aurelia-framework';


function clone(o) {
    return JSON.parse(JSON.stringify(o));
}


@containerless
export class SC{
    @bindable stream = null;

    constructor(){
    }

    edit(){
        this.backup = JSON.parse(JSON.stringify(this.stream));
    }

    cancelForm(){
        this.stream.editing = false;
        if (this.backup) {
            this.stream = clone(this.backup);
        }
    }
}
```

In my unit test, I initialize that property with the following:

```js
import {engine} from '../test-globals';
import {SC} from '../../../src/streams/sc';


describe('the SC module', () => {
    let sut;

    beforeEach(() => {
        sut = engine.createModelForUnitTest(SC);
        sut.stream = {name: 'Fun', slug: 'fun', description: 'loads to be had'};
    });

    it('lets users edit a stream and cancel edition', () => {
        sut.edit();
        sut.stream = {name: 'Some new name'};

        sut.cancelForm();

        expect(sut.stream.name).toEqual('Fun');
    });

});
```

This is my test-globals.js:

```js
// Contains objects that only need to be initialized/instantiated once for the
// whole test suite.

import {initialize} from 'aurelia-pal-browser';
import {templatingEngine} from 'aurelia-templating';
import {Container} from 'aurelia-dependency-injection';

// Initialize the browser PAL for tests
initialize();
export const container = new Container();
templatingEngine.initialize(container);
export const engine = templatingEngine;
```

This is the error I get:

```
ERROR [Chrome 46.0.2490 (Mac OS X 10.9.5) | the stream-card module | lets users edit a stream and cancel edition]: TypeError: Cannot read property 'setValue' of undefined
    at StreamCard.descriptor.set [as stream] (http://localhost:9876/base/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:2892:42)
    at Object.<anonymous> (http://localhost:9876/base/test/unit/streams/stream-card.spec.js:31:32)
ERROR [Chrome 46.0.2490 (Mac OS X 10.9.5) | the stream-card module | lets users edit a stream and cancel edition]: TypeError: Cannot read property 'getValue' of undefined
    at StreamCard.descriptor.get [as stream] (http://localhost:9876/base/jspm_packages/github/aurelia/templating@0.16.0/aurelia-templating.js:2888:49)
    at StreamCard.edit (http://localhost:9876/base/src/streams/stream-card.js:94:49)
    at Object.<anonymous> (http://localhost:9876/base/test/unit/streams/stream-card.spec.js:35:25)
```

If the property is not `@bindable`, the test passes. But the custom element of course doesn't work as I intend...

---

Update: this error happens when this test is run as part of a larger suite, but not if this is the only test I run.

**Comment by txels** [comment]
(this is a follow-up of a discussion with @PWKad on gitter)

**Comment by EisenbergEffect** [comment]
That is not how the templating engine is used anymore. That was a breaking change. See this set of tests for an example of proper usage: https://github.com/aurelia/templating/blob/master/test/behavior-testing.js

**Comment by txels** [comment]
Thanks! I just updated to latest pre-beta. I am now getting this error when using the new `TemplatingEngine` method:

```
engine = container.get(TemplatingEngine);
sut = engine.createViewModelForUnitTest(UserMenu);
...
TypeError: _aureliaPal.DOM.createMutationObserver is not a function
```

**Comment by EisenbergEffect** [comment]
Are you still initializing pal-browser?

**Comment by txels** [comment]
No. Should I?

**Comment by txels** [comment]
Posted a more complete trace to gitter: https://gitter.im/Aurelia/Discuss?at=56436fb35f3db8f60ab60a63
Would you rather follow the conversation here or there?

**Comment by EisenbergEffect** [comment]
Yes, that's where the implementation of that missing method comes from.

```
import {initialize} from 'aurelia-pal-browser';
initialize();
```

**Comment by txels** [comment]
Cool. Thanks for the quick response!

**Comment by txels** [comment]
Still, unfortunately, that doesn't solve my original issue. I still get:

```
ERROR [Chrome 46.0.2490 (Mac OS X 10.9.5) | the SC module | lets users edit a stream and cancel edition]: TypeError: Cannot read property 'setValue' of undefined
    at SC.descriptor.set [as stream] (http://localhost:9876/base/jspm_packages/github/aurelia/templating@0.17.1/aurelia-templating.js:2937:42)
    at Object.<anonymous> (http://localhost:9876/base/test/unit/streams/sc.spec.js:18:32)
```

...when assiging the bindable property in the test above.

**Comment by EisenbergEffect** [comment]
can you post your full, updated code?

**Comment by txels** [comment]
For that example, I updated `sc.spec.js` to:

```js
import {engine} from '../test-globals';
import {SC} from '../../../src/streams/sc';

describe('the SC module', () => {
    let sut;

    beforeEach(() => {
        sut = engine.createViewModelForUnitTest(SC);
        sut.stream = {name: 'Fun', slug: 'fun', description: 'loads to be had'};
    });

    it('lets users edit a stream and cancel edition', () => {
        sut.edit();
        sut.stream = {name: 'Some new name'};

        sut.cancelForm();

        expect(sut.stream.name).toEqual('Fun');
    });

});
```

And `test-globals` to:

```js
import {TemplatingEngine} from 'aurelia-templating';
import {Container} from 'aurelia-dependency-injection';
import {initialize} from 'aurelia-pal-browser';

initialize();
export const container = new Container();
export const engine = container.get(TemplatingEngine);
```

Is the fact that I am reusing a container an issue?

**Comment by EisenbergEffect** [comment]
I wouldn't re-use the container.

**Comment by txels** [comment]
OK. I'll try with that and report back.

**Comment by txels** [comment]
Yes, looks like re-creating the container doesn't get me into that issue. Many thanks again!

**Comment by txels** [comment]
This issue seems to have resurfaced after I updated to `beta1`. 

```
inner error: TypeError: _aureliaPal.DOM.createMutationObserver is not a function
    at makeRequestFlushFromMutationObserver (http://localhost:9876/base/jspm_packages/npm/aurelia-task-queue@1.0.0-beta.1/aurelia-task-queue.js:13:36)
    at new TaskQueue (http://localhost:9876/base/jspm_packages/npm/aurelia-task-queue@1.0.0-beta.1/aurelia-task-queue.js:59:41)
    at Object.invoke (http://localhost:9876/base/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:334:14)
    at InvocationHandler.invoke (http://localhost:9876/base/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:309:168)
    at Container.invoke (http://localhost:9876/base/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:557:25)
    at StrategyResolver.get (http://localhost:9876/base/jspm_packages/npm/aurelia-dependency-injection@1.0.0-beta.1/aurelia-dependency-injection.js:145:37)
```

Is this because of changes introduced in beta?

**Comment by txels** [comment]
Nevermind, my mistake. I had two versions of aurelia-pal-browser in JSPM, including the old one from `github:aurelia/pal-browser@0.3.0`.

With the version `npm:aurelia-pal-browser@1.0.0-beta.1` all works well.
