### ISSUE TITLE
BindingLanguage error after 1.2.4 update

### ISSUE THREAD

**Issue by AStoker** [aurelia/templating#334]
After getting the latest version, I am receiving this error on app start:
```
main.js:35 Error: A BindingLanguage must implement inspectTextContent(...)
    at TemplatingBindingLanguage.inspectTextContent (https://andrews-pc10:44301/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.4/aurelia-templating.js:692:13)
    at ViewCompiler._compileNode (https://andrews-pc10:44301/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.4/aurelia-templating.js:2077:79)
    at ViewCompiler._compileNode (https://andrews-pc10:44301/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.4/aurelia-templating.js:2097:33)
    at ViewCompiler.compile (https://andrews-pc10:44301/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.4/aurelia-templating.js:2054:12)
    at eval (https://andrews-pc10:44301/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.4/aurelia-templating.js:2685:49)
    at run (https://andrews-pc10:44301/jspm_packages/npm/core-js@2.3.0/modules/es6.promise.js:94:24)
    at eval (https://andrews-pc10:44301/jspm_packages/npm/core-js@2.3.0/modules/es6.promise.js:111:9)
    at flush (https://andrews-pc10:44301/jspm_packages/npm/core-js@2.3.0/modules/_microtask.js:22:11)
    at module.exports (https://andrews-pc10:44301/jspm_packages/npm/core-js@2.3.0/modules/_invoke.js:5:25)
    at queue.(anonymous function) (https://andrews-pc10:44301/jspm_packages/npm/core-js@2.3.0/modules/_task.js:36:9)
```
Not sure what happened. One moment I was on the previous version and everything worked, then I ran the `jspm update` command, and this started breaking.  
I'm kind of at a loss on where to go to start looking at what's going one here.

**Comment by AStoker** [comment]
This is currently my `main.js` file as well:
```
import {LogManager} from 'aurelia-framework';
import {ConsoleAppender} from 'aurelia-logging-console';
import {Api} from './api/Api';
import {HttpClient} from 'aurelia-fetch-client';
import 'tocca'; //Touch Events

import {ApiBaseURL} from 'utils/Constants';

LogManager.addAppender(new ConsoleAppender());
LogManager.setLevel(LogManager.logLevel.debug);

export function configure(aurelia) {
    aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-animator-css')
    .plugin('aurelia-dialog');

  //Uncomment the line below to enable animation.
    aurelia.use.plugin('aurelia-animator-css');

    aurelia.use.feature('resources');

    let container = aurelia.container;
    container.registerInstance("FlowApi", new Api(new HttpClient(), ApiBaseURL.FLOW));
    container.registerInstance("FormApi", new Api(new HttpClient(), ApiBaseURL.FORM));

  //Anyone wanting to use HTMLImports to load views, will need to install the following plugin.
  //aurelia.use.plugin('aurelia-html-import-template-loader')

    aurelia.start().then(a => a.setRoot()).catch(err => {console.error(err)});
}
```

**Comment by EisenbergEffect** [comment]
Check to see if you have forks.

**Comment by AStoker** [comment]
Already did that. No forks. 
Tried running `jspm update` again and I get this message:
```
 The following new package versions were substituted by install deduping:

   aurelia-framework 1.0.0-beta.1.2.2 -> 1.0.0-beta.1.1.4
   aurelia-history-browser 1.0.0-beta.1.2.0 -> 1.0.0-beta.1.1.4
   aurelia-loader-default 1.0.0-beta.1.2.1 -> 1.0.0-beta.1.1.3
   aurelia-logging-console 1.0.0-beta.1.2.0 -> 1.0.0-beta.1.1.4
   aurelia-pal-browser 1.0.0-beta.1.2.0 -> 1.0.0-beta.1.1.4
   aurelia-templating-binding 1.0.0-beta.1.2.2 -> 1.0.0-beta.1.1.2
   aurelia-templating-resources 1.0.0-beta.1.2.3 -> 1.0.0-beta.1.1.3
   aurelia-templating-router 1.0.0-beta.1.2.0 -> 1.0.0-beta.1.1.2
   aurelia-event-aggregator 1.0.0-beta.1.2.0 -> 1.0.0-beta.1.1.1
   aurelia-router 1.0.0-beta.1.2.1 -> 1.0.0-beta.1.1.3
   aurelia-task-queue 1.0.0-beta.1.2.0 -> 1.0.0-beta.1.1.1
   aurelia-dependency-injection 1.0.0-beta.1.2.2 -> 1.0.0-beta.1.1.5
   aurelia-binding 1.0.0-beta.1.3.3 -> 1.0.0-beta.1.2.2
```
But there were no issues, and it also says that there's no forks.

**Comment by AStoker** [comment]
I think my package config might be hosed, so I'm gonna try and remove the dependencies that are listed in the jspm section of the config, and add them back via `jspm install` to see if it gives it the kick in the shins it needs

**Comment by AStoker** [comment]
Okay, panic moment is over. Don't know what got hosed in the package config, but deleting all the aurelia package config lines, and then adding them back fixed something, I'm not complaining. Sorry for the distraction!

**Comment by AStoker** [comment]
Side note, unrelated. It seems that the way files are loaded up have changed. Some areas I now have to say `./SomeLocation` as opposed to `SomeLocation`

**Comment by EisenbergEffect** [comment]
This is outside the scope of Aurelia but relates to the module loader. It could be a change in the version of the loader you are using.

**Comment by danielmeza** [comment]
I had the same issue, I solved it by changing the module property on my typescript configuration file, I must set it on system.
