### ISSUE TITLE
New beta 3.0.4 ViewEngineHooksResource error

### ISSUE THREAD

**Issue by pixels4nickels** [aurelia/templating#397]
When updating to the latest 3.0.4 templating I am getting this error in Chrome Version 51.0.2704.84 (64-bit) on OS X:
`aurelia-templating.js:2993 Uncaught (in promise) ReferenceError: ViewEngineHooksResource is not defined
    at ModuleAnalyzer.analyze (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.4/aurelia-templating.js:2993:154)
    at http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.3.0.4/aurelia-templating.js:3144:53analyze @ aurelia-templating.js:2993(anonymous function) @ aurelia-templating.js:3144`

Rolling back to 3.0.3 resolves the error.

**Comment by EisenbergEffect** [comment]
There was a build configuration error. I've updated the release to 1.0.0-beta.3.0.5.
