### ISSUE TITLE
Cannot create html only custom element

### ISSUE THREAD

**Issue by dstroyrofworlds** [aurelia/templating#417]
I have my page:

```html
<template>
    <require from="../src/nmp-base-page.html"></require>

    <nmp-base-page>
        <div slot="header">My custom header content</div>
        <div slot="content">My body content</div>
        <div slot="footer">My custom header content</div>
    </nmp-base-page>

</template>
```

and my custom element:
```html
<template>
    <div>
        <slot name="header">You did not provide header content</slot>
    </div>
    <slot name="content">You did not provide content</slot>
    <div>
        <slot name="footer">You did not provide footer content</slot>
    </div>
</template>
```

This gives an error in the console:
```
Unhandled rejection TypeError: Cannot read property 'length' of undefined
    at ViewEngine.loadTemplateResources (http://localhost:9000/aurelia.bundle.js:3152:21)
    at http://localhost:9000/aurelia.bundle.js:3133:39
From previous event:
    at ViewEngine.loadViewFactory (http://localhost:9000/aurelia.bundle.js:3121:65)
    at RelativeViewStrategy.loadViewFactory (http://localhost:9000/aurelia.bundle.js:556:23)
    at HtmlBehaviorResource.load (http://localhost:9000/aurelia.bundle.js:3849:27)
    at ResourceDescription.load (http://localhost:9000/aurelia.bundle.js:2940:26)
    at ResourceModule.load (http://localhost:9000/aurelia.bundle.js:2883:23)
    at http://localhost:9000/aurelia.bundle.js:3225:41
From previous event:
    at ViewEngine.importViewResources (http://localhost:9000/aurelia.bundle.js:3194:50)
    at ViewEngine.loadTemplateResources (http://localhost:9000/aurelia.bundle.js:3164:17)
    at http://localhost:9000/aurelia.bundle.js:3133:39
From previous event:
    at ViewEngine.loadViewFactory (http://localhost:9000/aurelia.bundle.js:3121:65)
    at ConventionalViewStrategy.loadViewFactory (http://localhost:9000/aurelia.bundle.js:577:23)
    at HtmlBehaviorResource.load (http://localhost:9000/aurelia.bundle.js:3849:27)
    at http://localhost:9000/aurelia.bundle.js:4382:16
From previous event:
    at CompositionEngine.createController (http://localhost:9000/aurelia.bundle.js:4370:69)
    at CompositionEngine._createControllerAndSwap (http://localhost:9000/aurelia.bundle.js:4349:17)
    at CompositionEngine.compose (http://localhost:9000/aurelia.bundle.js:4429:19)
    at TemplatingEngine.compose (http://localhost:9000/aurelia.bundle.js:4665:36)
    at Aurelia.setRoot (http://localhost:9000/aurelia.bundle.js:16545:19)
    at http://localhost:9000/app.bundle.js:690:24
From previous event:
    at http://localhost:9000/app.bundle.js:689:21
    at http://localhost:9000/aurelia.bundle.js:16319:12
    at Array.<anonymous> (http://localhost:9000/aurelia.bundle.js:16248:19)
    at http://localhost:9000/aurelia.bundle.js:16309:27
From previous event:
    at http://localhost:9000/aurelia.bundle.js:16301:44
From previous event:
    at run (http://localhost:9000/aurelia.bundle.js:16296:24)
    at Object.<anonymous> (http://localhost:9000/aurelia.bundle.js:16323:1)
    at Object.<anonymous> (http://localhost:9000/aurelia.bundle.js:16324:30)
    at __webpack_require__ (http://localhost:9000/aurelia-bootstrap.bundle.js:53:30)
    at Object.<anonymous> (http://localhost:9000/aurelia.bundle.js:22558:1)
    at __webpack_require__ (http://localhost:9000/aurelia-bootstrap.bundle.js:53:30)
    at webpackJsonpCallback (http://localhost:9000/aurelia-bootstrap.bundle.js:24:23)
    at http://localhost:9000/aurelia.bundle.js:1:1
```

If I add a typescript file:
```Typscript
export class NmpBasePageCustomElement {   
}
```

and change the require i.e. remove the html extension - it works.

Am I missing something ?

The code producing the error:
```javascript
 ViewEngine.prototype.loadTemplateResources = function loadTemplateResources(registryEntry, compileInstruction, loadContext) {
    var resources = new ViewResources(this.appResources, registryEntry.address);
    var dependencies = registryEntry.dependencies;
    var importIds = void 0;
    var names = void 0;

    compileInstruction = compileInstruction || ViewCompileInstruction.normal;

    if (dependencies.length === 0 && !compileInstruction.associatedModuleId) {
      return Promise.resolve(resources);
    }

    importIds = dependencies.map(function (x) {
      return x.src;
    });
    names = dependencies.map(function (x) {
      return x.name;
    });
    logger.debug('importing resources for ' + registryEntry.address, importIds);

    return this.importViewResources(importIds, names, resources, compileInstruction, loadContext);
  };
```

**Comment by dstroyrofworlds** [comment]
If I debug it with a break point - the **registryEntry** is a string equal to my template html and not an javascript object.

**Comment by EisenbergEffect** [comment]
I have just tried out the code you provided and it worked without any problems. The one thing I did different was in the require path for the component. My guess is that your version is incorrect or that it isn't configured correctly with your module loader somehow.
