### ISSUE TITLE
@useShadowDOM Decorator Causes DOMException

### ISSUE THREAD

**Issue by elitecoder74** [aurelia/templating#464]
I'm submitting a bug report:

Classes that are decorated with @useShadowDOM cause a DOMException in aurelia.templating.js when the 'create' function is called from HtmlBehaviorResource .  The DOMException occurs when the function attempts to call 'attachShadow'.  This appears to be a result of the router view's initiation.

Here is the error received:

ERROR [app-router] DOMException: Failed to execute 'attachShadow' on 'Element': This element does not support attachShadow
    at HtmlBehaviorResource.create (http://localhost:49862/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:4010:30)
    at applyInstructions (http://localhost:49862/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2192:33)
    at ViewFactory.create (http://localhost:49862/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2413:9)
    at HtmlBehaviorResource.create (http://localhost:49862/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:4036:41)
    at eval (http://localhost:49862/jspm_packages/npm/aurelia-templating-router@1.0.0/router-view.js:163:51)
    at r (http://localhost:49862/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:33:7722)
    at i._settlePromiseFromHandler (http://localhost:49862/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:13044)
    at i._settlePromise (http://localhost:49862/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:13847)
    at i._settlePromise0 (http://localhost:49862/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:14548)
    at i._settlePromises (http://localhost:49862/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:15878)
    at r._drainQueue (http://localhost:49862/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:31:3148)
    at r._drainQueues (http://localhost:49862/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:31:3209)
    at drainQueues (http://localhost:49862/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:31:1238)

I am testing in browsers that have native support for Shadow DOM V1 (Google Chrome, Google Canary and Opera developer).

Also, if I inject 'Element' into the view-model that is not decorated with @shadowDOM, I am able to call 'attachShadow' successfully on the injected Element.

Finally, I have tested in both my personal ASP.NET Core project, as well as, the ASP.NET Core skeleton project for typescript.

**Comment by EisenbergEffect** [comment]
I don't understand what this had to do with the router. Please create an issue using our issue template and fill out the related info. Thanks.
