### ISSUE TITLE
Max call stack size exceeded when template within SVG element

### ISSUE THREAD

**Issue by timfish** [aurelia/templating#472]
**I'm submitting a bug report**

aurelia-templating@1.1.0

Windows 10
Node v6.6.0
NPM v3.10.3
JSPM v0.16.45

**Browsers**
- Chrome 53.0.2785.116
- nwjs 0.17.3-sdk

**Language:**
TypeScript

**Current behavior:**

```
aurelia-logging-console.js:54 ERROR [app-router] RangeError: Maximum call stack size exceeded
    at ViewResources._invokeHook (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:1276:63)
    at ViewCompiler.compile (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2531:17)
    at ViewCompiler._compileElement (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2732:28)
    at ViewCompiler._compileNode (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2565:23)
    at ViewCompiler.compile (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2534:12)
    at ViewCompiler._compileElement (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2732:28)
    at ViewCompiler._compileNode (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2565:23)
    at ViewCompiler.compile (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2534:12)
    at ViewCompiler._compileElement (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2732:28)
    at ViewCompiler._compileNode (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.1.0/aurelia-templating.js:2565:23)
```

`graph.html`

``` html
<template>
  <svg width="800" height="400" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
    <template replaceable part="contents">

    </template>
  </svg>
</template>
```

`graph.ts`

``` typescript
export class Graph {
}
```

`index.html`

``` html
<template>
  <require from="./graph"></require>

  <graph>
    <template replace-part="contents">
       <!--  I'm going to add my custom svg elements in here eventually -->
    </template>
  </graph>
</template>
```

If I comment out `<template replaceable part="contents"></template>` from within the `svg` element I no longer get the crash. Sometimes in chrome I'll even get "Aw, Snap!" and when I run in nwjs it normally takes down the whole app.

**Comment by timfish** [comment]
appears to occur with just a plain `<template></template>` within an svg too

**Comment by EisenbergEffect** [comment]
My guess is that this is just a limitation of SVG. SVG is very strict. Can you create a simple reproduction that we can test out?

**Comment by timfish** [comment]
I'll get a demo together. There is a Polymer [bug](https://github.com/Polymer/polymer/issues/1976) about the functionality being broken which has a [link](http://jsbin.com/wiqowo/31/edit?html,output) to an example which was apparently working at some point, although now doesn't due to `DOMException: Only secure origins are allowed`.

**Comment by timfish** [comment]
Occurs here:
https://gist.run/?id=c5e2cae39f9aec04e8d149a4026a4546

**Comment by timfish** [comment]
Some background on why they had issues in Polymer:

> Template elements with a svg parent have the same namespaceURI (http://www.w3.org/2000/svg), so the browser doesn't implement HTMLTemplateElement. The bootstrap code in 0.5 basically transplanted all child nodes of any svg-namespaced template into a new html-namespaced template, and then inserted that node back in its place.

**Comment by timfish** [comment]
@EisenbergEffect I'm using `aurelia-template-lint` which tells me it's bad to combine `if.bind` and `repeat.for` on a single element. [This issue](https://github.com/aurelia/binding/issues/250) seems to point out its definitely wrong, although everything is working fine as I've only been targeting electron where it seems to work.

However, now my app will also be targeting generic browsers and if I can't use `template` within `svg` what are my options?

**Comment by timfish** [comment]
`<slot>` still works within svg so rather than create further custom elements, my current workaround is:
```typescript
@inlineView('<template><slot if.bind="condition"></slot></template>')
export class SvgIf {
  @bindable public condition: boolean = true;
}
```
Which can be used like:
```html
<svg-if condition.bind="displayNote">
   <!-- conditional svg content -->
</svg-if>
```
Nasty but simple
