### ISSUE TITLE
@bindable Error invoking SVGAnalyzer. Check the inner error for details.

### ISSUE THREAD

**Issue by caperavensoftware** [aurelia/templating#490]
I get the following error when running tests on a project.
When I remove the @bindable from ```@bindable settingsOpen = false;``` on PragmaTabSheet in pragma-tabsheet.js then all the test pass with out any errors.
When you add the @bindable again you get the error below.

Any suggestions on how I can resolve this.
Is this a aurelia problem or a transpiling problem, node problem? 

```
    at createElement (node_modules/aurelia-binding/dist/commonjs/aurelia-binding.js:4432:29)
    at new SVGAnalyzer (node_modules/aurelia-binding/dist/commonjs/aurelia-binding.js:4441:9)
    at Object.invoke (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:436:12)
    at InvocationHandler.invoke (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:413:166)
    at Container.invoke (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:667:23)
    at StrategyResolver.get (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:133:35)
    at Container.get (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:600:39)
    at Object.invoke (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:466:103)
    at InvocationHandler.invoke (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:413:166)
    at Container.invoke (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:667:23)
    at StrategyResolver.get (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:133:35)
    at Container.get (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:600:39)
    at HtmlBehaviorResource.initialize (node_modules/aurelia-templating/dist/commonjs/aurelia-templating.js:3835:38)
    at getObserver (node_modules/aurelia-templating/dist/commonjs/aurelia-templating.js:3547:16)
    at PragmaTabSheet.descriptor.set [as settingsOpen] (node_modules/aurelia-templating/dist/commonjs/aurelia-templating.js:3612:7)
    at Context.<anonymous> (app/test/components/pragma-tab-sheet/pragma-tab-sheet-tests.js:152:37)
End Inner Error Stack
------------------------------------------------

    at new AggregateError (node_modules/aurelia-pal/dist/commonjs/aurelia-pal.js:36:11)
    at Container.invoke (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:669:13)
    at StrategyResolver.get (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:133:35)
    at Container.get (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:600:39)
    at Object.invoke (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:466:103)
    at InvocationHandler.invoke (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:413:166)
    at Container.invoke (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:667:23)
    at StrategyResolver.get (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:133:35)
    at Container.get (node_modules/aurelia-dependency-injection/dist/commonjs/aurelia-dependency-injection.js:600:39)
    at HtmlBehaviorResource.initialize (node_modules/aurelia-templating/dist/commonjs/aurelia-templating.js:3835:38)
    at getObserver (node_modules/aurelia-templating/dist/commonjs/aurelia-templating.js:3547:16)
    at PragmaTabSheet.descriptor.set [as settingsOpen] (node_modules/aurelia-templating/dist/commonjs/aurelia-templating.js:3612:7)
    at Context.<anonymous> (app/test/components/pragma-tab-sheet/pragma-tab-sheet-tests.js:152:37)
fail: PragmaTabSheet Tests done
TypeError: Cannot read property 'getOrCreateObserversLookup' of undefined
    at getObserver (node_modules/aurelia-templating/dist/commonjs/aurelia-templating.js:3550:38)
    at PragmaTabSheet.descriptor.set [as settingsOpen] (node_modules/aurelia-templating/dist/commonjs/aurelia-templating.js:3612:7)
    at Context.<anonymous> (app/test/components/pragma-tab-sheet/pragma-tab-sheet-tests.js:161:37)
fail: PragmaTabSheet Tests settingsOpenChanged, open
TypeError: Cannot read property 'getOrCreateObserversLookup' of undefined
    at getObserver (node_modules/aurelia-templating/dist/commonjs/aurelia-templating.js:3550:38)
    at PragmaTabSheet.descriptor.set [as settingsOpen] (node_modules/aurelia-templating/dist/commonjs/aurelia-templating.js:3612:7)
    at Context.<anonymous> (app/test/components/pragma-tab-sheet/pragma-tab-sheet-tests.js:169:37)
fail: PragmaTabSheet Tests settingsOpenChanged, closed
TypeError: Cannot read property 'getOrCreateObserversLookup' of undefined
    at getObserver (node_modules/aurelia-templating/dist/commonjs/aurelia-templating.js:3550:38)
    at PragmaTabSheet.descriptor.set [as settingsOpen] (node_modules/aurelia-templating/dist/commonjs/aurelia-templating.js:3612:7)
    at Context.<anonymous> (app/test/components/pragma-tab-sheet/pragma-tab-sheet-tests.js:177:37)
```

You can check the repository
https://github.com/pragmaproducts/pragma-tabsheet

**Comment by jdanyow** [comment]
Can you link to the file with the test? The error looks like something you'd get if you were attempting to test a component without setting up the container or using the testing package to configure things for you.

**Comment by caperavensoftware** [comment]
https://github.com/pragmaproducts/pragma-tabsheet/blob/master/test/components/pragma-tab-sheet/pragma-tab-sheet-tests.js

**Comment by jdanyow** [comment]
You'll need to use the testing infrastructure to ensure your component is staged properly for testing. More info here: http://aurelia.io/hub.html#/doc/article/aurelia/testing/latest/testing-components

**Comment by caperavensoftware** [comment]
what I don't understand is that when I used typescript it worked fine and all those tests passed as is with out any issues, but switching over to babel it now gives an issue.

I will try it anyway because I need this problem to go away but I am concerned that there is a difference between babel and typescript when it comes to how that works.

**Comment by jdanyow** [comment]
I'm guessing in the babel transpiled version, the bindable property is being assigned, causing the setter code to be executed.  `@bindable` creates a property getter/setter that uses aurelia's observerlocator.  If things are not wired up properly in the container you'll hit the error you're seeing.

Maybe in the typescript transpiled version of the class, the property isn't assigned.

**Comment by EisenbergEffect** [comment]
What's the status of this? Do we need to fix a bug?

**Comment by jdanyow** [comment]
I don't think so- @caperavensoftware are you all set with using aurelia-testing to ensure your environment is configured for testing components?
