### ISSUE TITLE
Error invoking SlotCustomAttribute

### ISSUE THREAD

**Issue by RichiCoder1** [aurelia/templating#530]
**I'm submitting a bug report**

* **Library Version:**
  * `aurelia-templating@1.3.0`
  * ` aurelia-webpack-plugin@https://github.com/aurelia/webpack-plugin.git#v2.0`,

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Webpack Version**
`webpack 2.2.1`

* **Browser:**
 Chrome 56

* **Language:**
TypeScript 2.2

**Current behavior:**
Utilizing layouts, I get an error when navigating to a page with the `slot` defined on an element.

Console Output:
```
ERROR [app-router] Error: Error invoking SlotCustomAttribute. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
Inner Error Stack:
Error: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
    at validateKey (http://localhost:6230/dist/main.bundle.js:21341:11)
    at Container.get (http://localhost:6230/dist/main.bundle.js:21538:5)
    at Object.invoke (http://localhost:6230/dist/main.bundle.js:21390:31)
    at Container.invoke (http://localhost:6230/dist/main.bundle.js:21625:23)
    at ProviderResolver.get (http://localhost:6230/dist/main.bundle.js:6371:72)
    at HtmlBehaviorResource.create (http://localhost:6230/dist/main.bundle.js:8378:56)
    at applyInstructions (http://localhost:6230/dist/main.bundle.js:6528:31)
    at ViewFactory.create (http://localhost:6230/dist/main.bundle.js:6749:7)
    at HtmlBehaviorResource.create (http://localhost:6230/dist/main.bundle.js:8390:39)
    at http://localhost:6230/dist/main.bundle.js:40446:49
```
It looks like the `element` dependency of `SlotCustomAttribute` is getting determined as `undefined` in `Container.invoke`. I'm not sure if this is a sympotn of router or of webpack.

/cc @jods4 in case it's the latter.

**Comment by jods4** [comment]
Duplicate of aurelia/pal-browser#17

**Comment by RichiCoder1** [comment]
It does appear to be...
