### ISSUE TITLE
repeat.for breaks inside custom element

### ISSUE THREAD

**Issue by andrevlins** [aurelia/templating#58]
In the following scenario the initial load works fine but when the "next" button is clicked the following exception occurs:
 `Uncaught TypeError: Cannot read property 'length' of undefined`(full stack at end).

scenario:

Using a custom element to layout a `repeater`within a div.

View:

```html
<template>
    <h3>${title}</h3>
    <button class="btn btn-default" click.delegate="dataSource.nextPage()">Next Page</button>
    <repro-layout>
        <template repeat.for="item of dataSource.data">
            ITEM ${item} <br/>
        </template>
    </repro-layout>
</template>
```

View Model:
```javascript
import {inject} from 'aurelia-framework';
import {ReproDataSource} from './repro-datasource';

@inject(ReproDataSource)
export class ReproVm {
    constructor(dataSource) {
        this.title = 'repro repeat error on custom element';
        this.dataSource = dataSource;
    }

    activate() {
        this.dataSource.load();
    }
}
```

Custom Element View:
```html
<template>
    <div style="background-color: yellow; padding: 20px;">
        <content></content>
    </div>
</template>
```

Custom Element View Model:
```javascript
import {customElement} from 'aurelia-framework';

@customElement('repro-layout')
export class ReproLayout {

}
```

Data Source Class:
```javascript
export class ReproDataSource {
    constructor() {
        this.data = [];
    }

    load() {
        this.data = [1,2,3,4,5,6,7,8,9,10];
    }

    nextPage() {
        this.data = [11,12,13,14,15,16,17,18,19,20];
    }

}
```

Error Stack:

TypeError: Cannot read property 'length' of undefined
    at ContentSelector.removeAt (http://localhost:1499/jspm_packages/github/aurelia/templating@0.10.3/content-selector.js:92:36)
    at ViewSlot.contentSelectorRemoveAll (http://localhost:1499/jspm_packages/github/aurelia/templating@0.10.3/view-slot.js:339:37)
    at Repeat.processItems (http://localhost:1499/jspm_packages/github/aurelia/templating-resources@0.10.0/repeat.js:108:24)
    at Repeat.itemsChanged (http://localhost:1499/jspm_packages/github/aurelia/templating-resources@0.10.0/repeat.js:98:18)
    at BehaviorPropertyObserver.execute._createClass.value.selfSubscriber (http://localhost:1499/jspm_packages/github/aurelia/templating@0.10.3/bindable-property.js:93:61)
    at BehaviorPropertyObserver.call (http://localhost:1499/jspm_packages/github/aurelia/templating@0.10.3/bindable-property.js:229:22)
    at TaskQueue.flushMicroTaskQueue (http://localhost:1499/jspm_packages/github/aurelia/task-queue@0.3.0/index.js:117:22)
    at MutationObserver.<anonymous> (http://localhost:1499/jspm_packages/github/aurelia/task-queue@0.3.0/index.js:53:28)

**Comment by EisenbergEffect** [comment]
Are you using shadow dom on any of these components? Can you check if it works correctly on Chrome vs. Firefox? I don't see that info here, but the stack trace makes me think it might be related.

**Comment by andrevlins** [comment]
It doesn't work on Chrome or Firefox.

**Comment by andrevlins** [comment]
I`m not using shadow dom

**Comment by EisenbergEffect** [comment]
Gotcha. I see now. The issue relates to the use of the `content` tag somehow. If you can create a repro on top of the navigation-skeleton, that would help me to look into this.

**Comment by andrevlins** [comment]
I can make it on navigation-skeleton but how do I submit this after? Not used to contributions.

**Comment by andrevlins** [comment]
Hi, Take a look at issue reproduction on skeleton-navigation in:

https://github.com/andrevlins/skeleton-navigation

Hope it helps.

**Comment by EisenbergEffect** [comment]
Good news. Whatever the bug was, it appears to be fixed on master. Look for a new release tomorrow.
