### ISSUE TITLE
Bindable with custom element doesn't work

### ISSUE THREAD

**Issue by tomasbonco** [aurelia/templating#78]
This code:
```
import {customElement, bindable } from 'aurelia-framework'

@customElement('value')
export class Value
{
	@bindable target
	@bindable min
	@bindable max
	@bindable doubleClick
}
```

Is throwing this error (four times):
```
Potentially unhandled rejection [1] TypeError: Cannot read property 'getObserversLookup' of undefined
    at new BehaviorInstance (http://localhost:9000/jspm_packages/github/aurelia/templating@0.10.3/behavior-instance.js:22:56)
    at HtmlBehaviorResource.create (http://localhost:9000/jspm_packages/github/aurelia/templating@0.10.3/html-behavior.js:206:36)
    at http://localhost:9000/jspm_packages/github/aurelia/templating@0.10.3/composition-engine.js:91:33
    at O (http://localhost:9000/jspm_packages/es6-module-loader.js:7:7439)
    at K (http://localhost:9000/jspm_packages/es6-module-loader.js:7:7071)
    at y.7.y.when (http://localhost:9000/jspm_packages/es6-module-loader.js:7:10745)
    at v.7.v.run (http://localhost:9000/jspm_packages/es6-module-loader.js:7:9781)
    at a.3.a._drain (http://localhost:9000/jspm_packages/es6-module-loader.js:7:1740)
    at 3.a.drain (http://localhost:9000/jspm_packages/es6-module-loader.js:7:1394)
    at MutationObserver.b (http://localhost:9000/jspm_packages/es6-module-loader.js:7:3302)
```

**Comment by EisenbergEffect** [comment]
Are you sure you have the latest versions of all the aurelia libraries?

**Comment by devmondo** [comment]
i confirm updating to latest aurelia, dont show this problem

**Comment by EisenbergEffect** [comment]
Ok, good to hear.

**Comment by PWKad** [comment]
@EisenbergEffect I can reproduce this on latest when DI'ing a class into a view-model.  Originally I put the @bindable on the class before upgrading a while back to get the `valueChanged` for free but I think this was bad practice anyway.  On update it started getting mad at me and using a customAttribute instead of a bindable fixed it.

I think this was ok at a point in time during alpha but shouldn't be a good practice so good to keep closed, just mentioning.
